# Generated by Django 3.2 on 2021-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_business_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='hood'),
        ),
    ]
